/* Question #1: 
What is the number of impressions in 2022 per age group across Facebook and Instagram? */

SELECT
      age_bucket_user,
      parent_company,
      SUM(impressions) AS total_impressions

FROM meta_revenue

WHERE years = '2022'

GROUP BY 1,2

ORDER BY 1,2;


-------------------------------------------------------------------------------------
/* Question #2: 
Have the number of conversions been trending upwards or downwards for Facebook
for the age bucket 18-24 and 25-34 over the last few years? */

SELECT
      years,
      SUM(conversions) AS total_conversions

FROM meta_revenue

WHERE age_bucket_user IN ('18-24' , '25-34') AND parent_company = 'Facebook'

GROUP BY 1

ORDER BY 1;


-------------------------------------------------------------------------------------
/* Question #3: 
A standard metric to analyze in the ads business is called conversion-per-click
which is defined as your total conversion value divided by the number of clicks.

Can you build the conversion-per-click metric and analyze how the metric is trending
for Instagram for the age bucket 18-24 over the last few years? */

SELECT
      years,
      AVG(conversions)/AVG(clicks) AS click_per_conversion

FROM meta_revenue

WHERE parent_company = 'Instagram' AND age_bucket_user = '18-24'

GROUP BY 1

ORDER BY 1;


-------------------------------------------------------------------------------------
/* Question #4: 
Create a column that summarizes the dates based on the calendar quarters in the year
(e.g., Q1 is 2022-01-01 to 2022-03-31). 

What is the revenue and number of conversions generated per quarter for
the SMB sales team in 2022? */

SELECT
      CONCAT('Q',date_part('quarter',dates)) AS quarter,
      SUM(revenue) AS total_revenue,
      SUM(conversions) AS total_conversion

FROM meta_revenue

WHERE sales_team LIKE '%SMB%' AND years = '2022'

GROUP BY 1

ORDER BY 1;


-------------------------------------------------------------------------------------
/* Question #5: 
What is the average amount of revenue per ad that is generated
per quarter for the SMB sales team in 2022? */

SELECT
TO_CHAR(dates,'"Q"Q') AS quarter,
SUM(revenue)/COUNT(DISTINCT ad_id)

FROM meta_revenue

WHERE sales_team LIKE '%SMB%' AND years = '2022'

GROUP BY 1

ORDER BY 1;


-------------------------------------------------------------------------------------
/* Question #6: 
Calculate the following metrics for the top 10 clients that have the highest amount of
revenue in 2022: 

Total revenue, total conversions, total clicks, conversions per click, and average revenue per conversion */

SELECT
			client_id,
      SUM(revenue) AS total_revenue,
      SUM(conversions) AS total_conversion,
      SUM(clicks) AS total_clicks,
      SUM(conversions)::numeric/SUM(clicks) AS conversions_per_click,
      SUM(revenue)::numeric/SUM(conversions) AS average_revenue_per_conversion
FROM meta_revenue
WHERE years = '2022'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


-------------------------------------------------------------------------------------
/* Question #7: 
What is the average annual revenue per sector of clients that work in the sectors
Insurance and Banking? */

SELECT
	UPPER(sector) AS sector,
  AVG(annual_revenue) AS annual_revenue
  
FROM meta_clients

WHERE UPPER(sector) IN ('INSURANCE','BANKING')

GROUP BY 1;


-------------------------------------------------------------------------------------
/* Question #8: 
Your manager wants to analyze the marketing spend percentage by country, but the data
is not 100% clean. He mentions that you can clean the country field by using
the sales team information, and shared the following mapping with you: 

UK = United Kingdom
FR = France
ES = Spain
IT = Italy
DACH = Germany

What is the average marketing spend percentage per country? */

SELECT
			COALESCE(country,
               CASE
               			 WHEN SPLIT_PART(sales_team,'_',2) ='UK' THEN 'United Kingdom'
                     WHEN SPLIT_PART(sales_team,'_',2) = 'FR' THEN 'France'
                     WHEN SPLIT_PART(sales_team,'_',2) = 'ES' THEN 'Spain'
                     WHEN SPLIT_PART(sales_team,'_',2) = 'IT' THEN 'Italy'
                     WHEN SPLIT_PART(sales_team,'_',2) = 'DACH' THEN 'Germany'
               END
              ) AS country,
      AVG(marketing_spend_perc)
      
FROM meta_clients

GROUP BY 1;


-------------------------------------------------------------------------------------
/* Question #9: 
The data seems to be much cleaner now! Your manager is interested in comparing
the revenue generated by Meta against the total marketing spend of the clients.

What is the total marketing spend in $ (annual revenue of the client multiplied by
marketing spend %) and the total revenue generated by Meta per client ID in 2022
for the cleaned up country values Spain and Italy? */

SELECT
			client_id,
      SUM(DISTINCT marketing_spend_perc * annual_revenue) AS marketing_spent,
      SUM(revenue)
      
FROM meta_clients AS clients
    JOIN meta_revenue
    USING (client_id,sales_team)

WHERE EXTRACT(YEAR FROM dates) = '2022'
		AND CASE WHEN clients.country IS NOT NULL THEN clients.country
            WHEN clients.sales_team LIKE '%ES%' THEN 'Spain'
            WHEN clients.sales_team LIKE '%IT%' THEN 'Italy'
            ELSE clients.country
       	END IN ('Spain', 'Italy')
       
GROUP BY 1;


-------------------------------------------------------------------------------------
/* Question #10:
Create a client list and calculate the customer penetration % for clients in 2022 with
an industry that matches consumer goods.

The customer penetration can be calculated as follows:
Meta revenue generated in one year divided by the marketing spend $

Show the clients with the lowest customer penetration first. */

SELECT
    client_id,
    SUM(revenue) / SUM(DISTINCT marketing_spend_perc * annual_revenue)
        AS customer_penetration
        
FROM meta_clients
    JOIN meta_revenue
    USING (client_id)
    
WHERE EXTRACT(YEAR FROM dates) = '2022'
		AND UPPER(industry) LIKE '%CONSUMER GOODS%'
    
GROUP BY 1

ORDER BY 2 ASC;


-------------------------------------------------------------------------------------
/* Question #11: 
Reuse the answer of question 4.

Clean up the industry data and calculate the customer penetration for the clients
in the Retail & Consumer Goods industries based on the Meta revenue data from 2022?

The following values should fall under Retail & Consumer Goods: retail, Retail,
Consumer Goods, RCG, Retail & Consumer Goods. */

SELECT
    client_id,
    SUM(revenue) / SUM(DISTINCT marketing_spend_perc * annual_revenue)
        AS customer_penetration
        
FROM meta_clients
    JOIN meta_revenue
    USING (client_id)
    
WHERE EXTRACT(YEAR FROM dates) = '2022'
		AND REGEXP_LIKE(industry, 'retail|Retail|Consumer Goods|RCG|Retail & Consumer Goods', 'i')
    
GROUP BY 1
;


-------------------------------------------------------------------------------------
/* Question #12: 
Finally, your manager is interested in understanding how the customer penetration % of our biggest clients has changed year over year based on the changes in the revenue generated by Meta.

We can assume that the annual revenue of the client remains consistent.

Calculate the customer penetration % for every available year that we have Meta revenue available for for the client ID “Client_1010” */

SELECT
    EXTRACT(YEAR FROM dates),
    SUM(revenue) / SUM(DISTINCT marketing_spend_perc * annual_revenue)
        AS customer_penetration
        
FROM meta_clients
		JOIN meta_revenue
		USING (client_id)
    
WHERE client_id = 'Client_1010'

GROUP BY 1
;


-------------------------------------------------------------------------------------
/* QUESTION #13
The clients that have a client ID with a number between 0 and 1000 are 
the earliest are most loyal Meta customers and need to be treated with
the best care possible.

Your manager wants to understand how the sales teams performed on these 
customers over the last years.

What is the total revenue generated by Meta per year on clients that have
a client ID with a number between 0 and 1000? */

SELECT
    EXTRACT(YEAR FROM dates),
    SUM(revenue)

FROM meta_revenue

WHERE SPLIT_PART(client_id,'_',2)::numeric BETWEEN 0 AND 1000

GROUP BY 1

ORDER BY 1;


-------------------------------------------------------------------------------------
/* QUESTION #14
Your manager mentions that the client information of long term clients
tends to not get updated regularly since the clients are already in the system
for such a long time. He asks you to check this.

What is the average number of days since the client information was
last updated for clients that have a client ID with a number between 0 and 1000? */

SELECT
    AVG(CURRENT_DATE - last_updated_date)
  
FROM meta_clients

WHERE CAST(SUBSTR(client_id, 8, 20) AS INT) BETWEEN 0 AND 1000;


-------------------------------------------------------------------------------------
/* QUESTION #15
What is the total revenue generated by Meta in 2022 and the average number
of days since the client information was last updated for clients
with a client ID with a number between 0 and 1000 versus all the other clients? */

SELECT
    CASE
        WHEN SPLIT_PART(mr.client_id,'_',2)::numeric BETWEEN 0 AND 1000 THEN 'Long Term Clients'
        ELSE 'Other Clients'
    END AS client_group,
    SUM(revenue) AS total_revenue,
    AVG(CURRENT_DATE - last_updated_date) AS avg_days_since_update 
    
FROM meta_revenue AS mr
    LEFT JOIN meta_clients AS mc
    USING(client_id)

WHERE EXTRACT (YEAR FROM dates) = '2022'

GROUP BY 1;


-------------------------------------------------------------------------------------
/* QUESTION #16
Count how many attendees each type of offsite has had over the last few years.
Create the following offsite categories:
1. Drinks
2. Laser tag
3. Tennis
4. Mario Kart
5. Bubble Football
6. In case there are activities missing, populate the column with
“No Offsite Activity” to make sure all columns are populated. */

WITH team_size AS(
  
  SELECT
  			sales_team,
  			COUNT(DISTINCT (first_name,last_name,date_of_birth)) AS attendee_count
  
	FROM meta_employees
  
  GROUP BY 1
)


SELECT
    CASE
        WHEN REGEXP_LIKE(offsite_activity, 'Lazer Tag|Lasertag|Pew pew pew pew lazers') THEN 'Laser tag'
        WHEN REGEXP_LIKE(offsite_activity, 'Drinkssss|Drinks') THEN 'Drinks'
        WHEN offsite_activity = 'Tennis' THEN 'Tennis'
        WHEN offsite_activity = 'Mario Kart Tournament' THEN 'Mario Kart'
        WHEN LOWER(offsite_activity) = 'bubble football' THEN 'Bubble Football'
        ELSE 'No Offsite Activity'
    END AS activity_type,
    SUM(attendee_count) AS total_attendees
    
FROM meta_offsites
    JOIN team_size
    USING(sales_team)

GROUP BY 1;



-- More Elegant Solution:
SELECT
    CASE
        WHEN offsite_activity LIKE '%Drinks%' THEN 'Drinks'
        WHEN offsite_activity IN ('Tennis', 'Mario Kart Tournament') THEN offsite_activity
        WHEN REGEXP_LIKE(offsite_activity, 'laser|lazer|tag', 'i') THEN 'Laser tag'
        WHEN REGEXP_LIKE(offsite_activity, 'Football', 'i') THEN 'Bubble Football'
        WHEN offsite_activity = '' THEN 'No Offsite Activity'
        ELSE 'Error'     
    END AS offsite_category,
    COUNT(*) AS num_attendees
       
FROM meta_employees employees
		 LEFT JOIN meta_offsites offsites
     ON employees.sales_team = offsites.sales_team
     
GROUP BY offsite_category;


-------------------------------------------------------------------------------------
/* QUESTION #17
During the business reviews, the leadership wants to have a holistic
overview of sales performance metrics and culture metrics in a single table
for all sales teams.

Show the total revenue generated in 2021 and the number of offsite activities
each sales team has had in one table for all sales teams. 

If offsite activities are missing, you can assume nothing happened and
we should not count the activity. */

WITH year_fixed_meta_revenue AS (
  
  SELECT
        date_part('YEAR',dates) AS year,
        sales_team,
        revenue
  
	FROM meta_revenue
)


SELECT
    m1.sales_team,
    SUM(revenue) AS total_revenue,
    COUNT(DISTINCT offsite_activity) FILTER(WHERE offsite_activity != '') AS num_offsites
    
FROM meta_offsites AS m1
    JOIN year_fixed_meta_revenue AS m2
    ON m1.sales_team = m2.sales_team
    AND m1.year = m2.year
    
WHERE m1.year = 2021

GROUP BY 1;


--another solution:
SELECT revenue.sales_team,
			 SUM(revenue.revenue) AS total_revenue,
       COUNT(DISTINCT offsites.offsite_activity) AS num_offsites
       
FROM meta_revenue revenue
		 LEFT JOIN meta_offsites offsites
     ON revenue.sales_team = offsites.sales_team 
     
WHERE EXTRACT(YEAR FROM revenue.dates) = 2021
			AND offsites.year = 2021
      
GROUP BY revenue.sales_team;


-------------------------------------------------------------------------------------
/* QUESTION #18
After sharing the table with Your manager, he mentions that the leadership team
also wants to include a metric about how clean each sales team keeps the client
data.*/

WITH year_fixed_meta_revenue AS (
  
  SELECT
        date_part('YEAR',dates) AS year,
        sales_team,
        revenue,
  			client_id
  
	FROM meta_revenue
)


SELECT
    m1.sales_team,
    SUM(revenue) AS total_revenue,
    COUNT(DISTINCT offsite_activity) FILTER(WHERE offsite_activity != '') AS num_offsites,
    AVG((CURRENT_DATE - last_updated_date)::INT) AS avg_days_since_update
      
FROM meta_offsites AS m1
    JOIN year_fixed_meta_revenue AS m2
    ON m1.sales_team = m2.sales_team
    AND m1.year = m2.year
    JOIN meta_clients AS m3
    ON m3.client_id = m2.client_id

WHERE m1.year = 2021

GROUP BY 1;

